CREATE TABLE eco_code
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code  VARCHAR(255)                            NOT NULL,
    label VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_eco_code PRIMARY KEY (id)
);

CREATE TABLE iban
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    budget_year INTEGER                                 NOT NULL,
    code        VARCHAR(255)                            NOT NULL,
    parent_cdc  VARCHAR(255)                            NOT NULL,
    iban        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_iban PRIMARY KEY (id)
);

CREATE TABLE locality
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cdc        VARCHAR(255),
    parent_cdc VARCHAR(255),
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_locality PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id INTEGER NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    username    VARCHAR(20),
    email       VARCHAR(50),
    password    VARCHAR(120),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);